<style>
    .lib-footer-wrap .left {
        width: 50%;
        float: left;
        padding-left: 10px;
    }
    .lib-footer-wrap .right {
        margin-left: 50%;
        text-align: right;
        padding-right: 5px;
    }
    .clear {
        clear: both;
    }
    .lib-footer-wrap {
        width: 63%;
        margin-left: 18%;
        margin-bottom: 10px;
        color: #adb0b5;
    }
    small a {
        text-decoration: none;
        font-size: 10px !important;
        font-weight: bold;
    }
    .lib-footer-wrap a {
        text-decoration: none;
        font-size: inherit !important;
        color: inherit;
    }
</style>


<div class="lib-footer-wrap">
    <div class="left">
        <small style="font-size: 10px;"> Generated by Modern Library System </small>
    </div>
    <div class="right">
        <small style="font-size: 10px;"> A product of Modern Library Inc </small>
    </div>
    <div class="clear"></div>
</div>